import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Modal as RNModal,
  Pressable,
  Alert,
  Share,
  ScrollView,
} from 'react-native';
import { COLORS, SPACING, FONT_SIZE, BORDER_RADIUS } from '../constants';
import { useFitnessStore } from '../stores/fitnessStore';
import { useNutritionStore } from '../stores/nutritionStore';
import { useGamificationStore } from '../stores/gamificationStore';

interface ExportModalProps {
  visible: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ visible, onClose }) => {
  const [exporting, setExporting] = useState(false);
  const { activities, history, prs } = useFitnessStore();
  const { getTotalNutrition, goal: nutritionGoal, meals } = useNutritionStore();
  const { currency, achievements } = useGamificationStore();

  const totals = getTotalNutrition();

  const generateExportText = (): string => {
    const totalActivityTime = activities.reduce((sum, a) => {
      const parts = a.time.split(':').map(Number);
      return sum + (parts.length === 3 ? parts[0] * 60 + parts[1] + parts[2] / 60 : parts[0] + parts[1] / 60);
    }, 0);
    
    const unlockedAchievements = achievements.filter(a => a.unlockedAt);

    return `📊 HEALTH DATA EXPORT - ${new Date().toLocaleDateString()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🏃 ACTIVITIES (${activities.length})
Total Distance: ${activities.reduce((sum, a) => sum + a.distance, 0).toFixed(1)} km
Total Time: ${Math.round(totalActivityTime)} minutes
Total Calories: ${activities.reduce((sum, a) => sum + a.calories, 0)} cal

Recent Activities:
${activities.slice(0, 5).map((a) => `• ${a.name} - ${a.type} - ${a.distance}km - ${a.time}`).join('\n')}

💪 WORKOUT HISTORY (${history.length})
${history.slice(0, 3).map((w) => `• ${w.name} - ${w.date} - ${w.duration}min - ${w.calories}cal`).join('\n')}

🥗 NUTRITION
Today's Calories: ${totals.calories} / ${nutritionGoal.calories}
Protein: ${totals.protein}g / ${nutritionGoal.protein}g
Carbs: ${totals.carbs}g / ${nutritionGoal.carbs}g
Fat: ${totals.fat}g / ${nutritionGoal.fat}g

🏆 ACHIEVEMENTS (${unlockedAchievements.length} earned)
${unlockedAchievements.map(a => `• ${a.icon} ${a.name} (${a.unlockedAt || 'N/A'})`).join('\n')}

💰 GAMIFICATION
Coins: ${currency.coins} | Gems: ${currency.gems}

📈 PERSONAL RECORDS
${prs.map((p) => `• ${p.exercise}: ${p.weight}kg (${p.date})`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by UniversalHealth App
`;
  };

  const handleExport = async () => {
    setExporting(true);
    try {
      const content = generateExportText();
      await Share.share({
        message: content,
        title: 'Health Data Export',
      });
    } catch (error) {
      Alert.alert('Export Failed', 'Unable to export data. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <RNModal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Export Data</Text>
          <Pressable onPress={onClose} style={styles.closeButton}>
            <Text style={styles.closeText}>✕</Text>
          </Pressable>
        </View>

        <ScrollView style={styles.content}>
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>📋 Export Summary</Text>
            <View style={styles.statsCard}>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Activities</Text>
                <Text style={styles.statValue}>{activities.length}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Total Distance</Text>
                <Text style={styles.statValue}>{activities.reduce((sum, a) => sum + a.distance, 0).toFixed(1)} km</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Calories Burned</Text>
                <Text style={styles.statValue}>{activities.reduce((sum, a) => sum + a.calories, 0)}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Workouts</Text>
                <Text style={styles.statValue}>{history.length}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Personal Records</Text>
                <Text style={styles.statValue}>{prs.length}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Achievements</Text>
                <Text style={styles.statValue}>{achievements.filter(a => a.unlockedAt).length}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Coins</Text>
                <Text style={styles.statValue}>{currency.coins}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Gems</Text>
                <Text style={styles.statValue}>{currency.gems}</Text>
              </View>
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>🥗 Today's Nutrition</Text>
            <View style={styles.statsCard}>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Calories</Text>
                <Text style={styles.statValue}>{totals.calories} / {nutritionGoal.calories}</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Protein</Text>
                <Text style={styles.statValue}>{totals.protein}g / {nutritionGoal.protein}g</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Carbs</Text>
                <Text style={styles.statValue}>{totals.carbs}g / {nutritionGoal.carbs}g</Text>
              </View>
              <View style={styles.statRow}>
                <Text style={styles.statLabel}>Fat</Text>
                <Text style={styles.statValue}>{totals.fat}g / {nutritionGoal.fat}g</Text>
              </View>
            </View>
          </View>

          <View style={styles.section}>
            <Text style={styles.sectionTitle}>🏆 Recent Achievements</Text>
            <View style={styles.achievementsGrid}>
              {achievements.filter(a => a.unlockedAt).slice(0, 6).map((achievement) => (
                <View key={achievement.id} style={styles.achievementItem}>
                  <Text style={styles.achievementIcon}>{achievement.icon}</Text>
                  <Text style={styles.achievementName}>{achievement.name}</Text>
                </View>
              ))}
            </View>
          </View>
        </ScrollView>

        <View style={styles.footer}>
          <Pressable
            style={[styles.exportButton, exporting && styles.exportButtonDisabled]}
            onPress={handleExport}
            disabled={exporting}
          >
            <Text style={styles.exportButtonText}>
              {exporting ? '📤 Exporting...' : '📤 Share Data'}
            </Text>
          </Pressable>
          <Text style={styles.tipText}>
            💡 Your data will be shared as text that can be saved anywhere
          </Text>
        </View>
      </View>
    </RNModal>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  title: {
    fontSize: FONT_SIZE.xl,
    fontWeight: '700',
    color: COLORS.text,
  },
  closeButton: {
    padding: SPACING.sm,
  },
  closeText: {
    fontSize: FONT_SIZE.lg,
    color: COLORS.textSecondary,
  },
  content: {
    flex: 1,
    padding: SPACING.md,
  },
  section: {
    marginBottom: SPACING.lg,
  },
  sectionTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: SPACING.sm,
  },
  statsCard: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  statLabel: {
    fontSize: FONT_SIZE.md,
    color: COLORS.textSecondary,
  },
  statValue: {
    fontSize: FONT_SIZE.md,
    fontWeight: '600',
    color: COLORS.text,
  },
  achievementsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  achievementItem: {
    width: '31%',
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
    alignItems: 'center',
  },
  achievementIcon: {
    fontSize: 28,
    marginBottom: SPACING.xs,
  },
  achievementName: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  footer: {
    padding: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  exportButton: {
    backgroundColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
    alignItems: 'center',
  },
  exportButtonDisabled: {
    opacity: 0.6,
  },
  exportButtonText: {
    color: '#fff',
    fontSize: FONT_SIZE.md,
    fontWeight: '600',
  },
  tipText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: SPACING.sm,
  },
});

export default ExportModal;
